### ISSUE TITLE
Change allocated abilities

### ISSUE THREAD

**Issue by luis-figueiredo** [CyclopsMC/EverlastingAbilities#108]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

If this already exists please close this issue (and please tell me how to do it in the process). I'm new to the mod.
It'd be nice if you could, depending on a config option, be allowed to change which abilities you have currently equipped. I was scouring the config file and couldn't find anything related to that.
As I understand it, right now, after you've selected your abilities, there's no way to reset them or in any way change your choice, which makes for a horrible new player experience.

**Comment by rubensworks** [comment]
> As I understand it, right now, after you've selected your abilities, there's no way to reset them or in any way change your choice

The Ability Bottle is the item that allows you to remove and re-add abilities to your player. You should receive one for free when starting a new world. Does this solve your problem?

**Comment by luisrpfigueiredo** [comment]
Thank you for answering. Yes, it does :)

I tossed it away because it came with an ability I didn't want/need. Didn't realise it was different from the other ability totems that drop from mobs and that it allows me to remove allocated abilities.

It's kind of counter intuitive - it looks the same as all other totems and such. Since I'm here, will leave a suggestion: One option would be to give every totem you get the option to add or remove abilities from the player. That way, even if you lose your original, you can always get more.

A different approach would be to make the ability bottle craftable :) Maybe it already is not sure.

Just for clarification, in case I'm spewing bullshit: playing project ozone 3, I have never played the mod standalone.

Anyway thanks for the help, question cleared  :)

**Comment by rubensworks** [comment]
> It's kind of counter intuitive - it looks the same as all other totems and such

No it doesn't, it's a different item with a different icon.

> A different approach would be to make the ability bottle craftable :) Maybe it already is not sure.

It is craftable.
