### ISSUE TITLE
in mc 1.20.1 totems in chest have "none" abilities

### ISSUE THREAD

**Issue by krjencik** [CyclopsMC/EverlastingAbilities#231]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Totems generated in chests have no abilities on them

#### Steps to reproduce the problem:

1. ... just download this mod

#### Expected behaviour:
totems generated in chests will have abilities

____

#### Versions:

- This mod: EverlastingAbilities-1.20.1-2.0.6.jar
- Minecraft: 1.20.1
- Forge: 47.0.35

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by alezhito18** [comment]
please fix it as soon as possible, hopefully it will be fixed in a few hours, I'm going to play with my friends including your mod in my modpack of more than 60 mods, I like your mod, I've always used it since version 1.16.5 but it already bothers me It was necessary to update minecraft to the latest version, so the mod has this little problem

**Comment by rubensworks** [comment]
@alezhito18 I'm not sure if you realize that you're being very rude.
I work on this mod for free, so it's not very polite for you to expect that I immediately fix your problems.

**Comment by alezhito18** [comment]
I'm sorry but you misunderstood, I just said hopefully the solutions soon
and if you can'tyI'm sorry but you misunderstood, I just said hopefully
solutions soon and if you can't no problem, I am no one to tell you what to
do, I have only reported the error, it does not have to be so fragile for
my comment
