### ISSUE TITLE
Totem Combining: Result Visible

### ISSUE THREAD

**Issue by Dystinct** [CyclopsMC/EverlastingAbilities#56]
According to the project page, unless this has changed or can be changed in the config, you are able to see the result of crafting totems together (https://imgur.com/JhefC1u) unlike in your [demonstration](
https://media-elerium.cursecdn.com/attachments/209/995/schermafbeelding-2017-05-26-om-10.png) image.

**Comment by rubensworks** [comment]
Yes, this has changed because of the crafting changes in MC 1.12. Recipes are fully handled server-side now, which makes it impossible for clients to see this "unknown" ability.

That "unknown" ability type was introduced because the player would get a random ability each type the recipe was attempted, so it could just retry until a good one was found. In 1.12, this is now fully deterministic, so this is not an issue anymore.

**Comment by Dystinct** [comment]
Thank you for the clarification!
