### ISSUE TITLE
:bug: Crash trying to Recycle totems

### ISSUE THREAD

**Issue by Nachtflame** [CyclopsMC/EverlastingAbilities#71]
#### Short description:
When attempting to recycle Ability Totems, client crashes completely back to launcher.

#### Expected behaviour:
Place required number of totems into crafting grid -> pull out *new* totem

#### Actual behaviour:
Place required number of totems into crafting grid, crash back to launcher.

#### Steps to reproduce the problem:

Place required number of totems into any grid.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- Everlasting Abilities: 1.3.7
- CyclopsCore: 0.10.23
- Minecraft: 1.12.2
- Forge: 2562

#### Log file:
[crash-2017-12-18_13.58.53-client.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/1569605/crash-2017-12-18_13.58.53-client.txt)

##Extra Note:
I did just realize that the pack also contains NoMoreRecipeConflict, which may/may not be trying to check all the available recipes when recycling..

**Comment by rubensworks** [comment]
Update to the latest CC version, that'll fix it.

**Comment by trogarus** [comment]
Not sure if my situation is related to this or not because I get no actual game crash log. HOWEVER, I do get a pid log error that points to everlasting abilities. After being afk a while playing single player, I just get bounced back to the launcher telling me there was a crash, but no crash log to be found on this issue.

CyclopsCore-1.12.2-0.10.24
EverlastingAbilities-1.12.2-1.3.9
Forge 2560
Minecraft 1.12.2

[hs_err_pid6440.log](https://github.com/CyclopsMC/EverlastingAbilities/files/1572266/hs_err_pid6440.log)

[hs_err_pid7988.log](https://github.com/CyclopsMC/EverlastingAbilities/files/1572267/hs_err_pid7988.log)

**Comment by trogarus** [comment]
Oh, and here is the fml and latest logs as well. Nothing showing there either.

[fml-client-latest.log](https://github.com/CyclopsMC/EverlastingAbilities/files/1572274/fml-client-latest.log)

[latest.log](https://github.com/CyclopsMC/EverlastingAbilities/files/1572275/latest.log)

**Comment by josephcsible** [comment]
Not related. That's your actual JVM crashing, not just the game crashing.

**Comment by trogarus** [comment]
Hmmm. thanks for the reply on that. Guess I'll have to look there and try to find out why the jvm is crashing.
